#!/usr/bin/env python3
"""Regenerate file_list.txt for the SurfZone DEM source (NOT part of the build).

The build itself just fetches the URLs in file_list.txt — no API calls, no key minting.
Re-run this only when the public subscription key rotates or the EA ships a new vintage:

  python harvest.py            # sweeps the Defra survey tile API, rewrites file_list.txt

The Defra "survey" portal (https://environment.data.gov.uk/survey) is a Next.js front end over
an OGC/JSON backend. Acquisition is two unauthenticated HTTPS calls — no login, no AOI job/poll:

  index:    POST .../backend/catalog/api/tiles/collections/survey/search   (GeoJSON Polygon, 4326)
            → results[] each with product.id, tile.id (OS 5km, e.g. "SZ0590"), a download uri
  download: GET  {TILE_BASE}/<product>/<year>/<res>/<tile.id>?subscription-key=<KEY>
            → application/zip holding SurfZone_DEM_2019_<tile>_2m.tif (+ sidecars)

KEY is a public client-side key baked into the site's JS bundle (currently "dspui"); it's
unauthenticated by design but not contractually stable, so pin it here — rotation is a one-liner.
We sweep England's coast in coarse cells and union the tile ids (one search caps its result set,
so a single national polygon would truncate). ~1301 tiles, ~4 GB. Stdlib only, no pipeline coupling.
"""

import json
import sys
import urllib.request

SEARCH = "https://environment.data.gov.uk/backend/catalog/api/tiles/collections/survey/search"
TILE_BASE = "https://environment.data.gov.uk/tiles/collections/survey"
PRODUCT, YEAR, RES = "surfzone_dem_2019", "2019", "2"
KEY = "dspui"
BBOX = (-5.9, 49.8, 2.0, 56.0)  # England coast (incl. Scilly); SurfZone is England-only
STEP = 0.8                      # cell size in degrees — small enough that no cell truncates
HEADERS = {"Content-Type": "application/geo+json", "Accept": "*/*",
           "Origin": "https://environment.data.gov.uk",
           "Referer": "https://environment.data.gov.uk/survey"}


def tile_url(tile_id):
    return f"{TILE_BASE}/{PRODUCT}/{YEAR}/{RES}/{tile_id}?subscription-key={KEY}"


def cells(bbox, step):
    w, s, e, n = bbox
    la = s
    while la < n:
        lo = w
        while lo < e:
            yield (lo, la, min(lo + step, e), min(la + step, n))
            lo += step
        la += step


def search(w, s, e, n):
    body = json.dumps({"type": "Polygon",
                       "coordinates": [[[w, s], [e, s], [e, n], [w, n], [w, s]]]}).encode()
    req = urllib.request.Request(SEARCH, data=body, headers=HEADERS)
    with urllib.request.urlopen(req, timeout=60) as r:
        return json.load(r).get("results", [])


def harvest():
    tiles, errors = set(), 0
    grid = list(cells(BBOX, STEP))
    for i, c in enumerate(grid, 1):
        try:
            for res in search(*c):
                if res["product"]["id"] == PRODUCT:
                    tiles.add(res["tile"]["id"])
        except Exception as ex:
            errors += 1
            print(f"  cell {i}/{len(grid)} failed: {ex}")
        if i % 10 == 0:
            print(f"  {i}/{len(grid)} cells, {len(tiles)} tiles")
    if errors:
        print(f"WARNING: {errors} cell(s) failed — coverage may be incomplete; re-run.")
    return sorted(tiles)


def write_file_list(tiles, path):
    header = (
        f"# SurfZone DEM 2019 (Environment Agency, England, 2 m) — OGL v3.0. {len(tiles)} OS 5km\n"
        f"# tiles, fetched as per-tile ZIPs from the Defra survey tile API over public HTTPS (the\n"
        f"# ?subscription-key={KEY} below is a public client-side key, no login). Generated by\n"
        f"# harvest.py — re-run it if the key rotates or the EA ships a new vintage.\n")
    with open(path, "w") as f:
        f.write(header)
        f.writelines(tile_url(t) + "\n" for t in tiles)


def _check():
    assert tile_url("SZ0590") == (
        "https://environment.data.gov.uk/tiles/collections/survey/"
        "surfzone_dem_2019/2019/2/SZ0590?subscription-key=dspui")
    g = list(cells((0.0, 0.0, 1.6, 0.8), 0.8))  # 2 cells wide, 1 tall; clamps the last edge
    assert len(g) == 2 and g[0] == (0.0, 0.0, 0.8, 0.8) and g[1][2] == 1.6
    print("harvest.py self-check ok")


if __name__ == "__main__":
    if sys.argv[1:2] == ["--check"]:
        _check()
    else:
        path = f"{sys.path[0]}/file_list.txt"
        tiles = harvest()
        if not tiles:
            sys.exit("no tiles found — the key may have rotated or the API moved; check the site.")
        write_file_list(tiles, path)
        print(f"wrote {len(tiles)} tile URLs to {path}")
